### ISSUE TITLE
Using CSS grid for positioning items rather than top/left

### ISSUE THREAD

**Issue by sebastianwebb** [gridstack/gridstack.js#1012]
I see you use CSS rules to position the items, with position: absolute and top/left. Could these be substituted for CSS grid line coordinates without breaking the script?

Thanks for building and sharing an awesome tool!

Sebastian

**Comment by adumesny** [comment]
@sebastianwebb could you give a concrete example and what the benefit would be ?

right now the output CSS from sass looks like this for 12 column default

```css
.grid-stack > .grid-stack-item {
  min-width: 8.3333333333%;
  position: absolute;
  padding: 0;
}

.grid-stack>.grid-stack-item[data-gs-width='1'] {
  width: 8.3333333333%;
}
.grid-stack>.grid-stack-item[data-gs-x='1'] {
  left: 8.3333333333%;
}
.grid-stack>.grid-stack-item[data-gs-min-width='1'] {
  min-width: 8.3333333333%;
}
.grid-stack>.grid-stack-item[data-gs-max-width='1'] {
  max-width: 8.3333333333%;
}
.grid-stack>.grid-stack-item[data-gs-width='2'] {
  width: 16.6666666667%;
}
.grid-stack>.grid-stack-item[data-gs-x='2'] {
  left: 16.6666666667%;
}
.grid-stack>.grid-stack-item[data-gs-min-width='2'] {
  min-width: 16.6666666667%;
}
.grid-stack>.grid-stack-item[data-gs-max-width='2'] {
  max-width: 16.6666666667%;
}
etc...
```

**Comment by RadoiAndrei** [comment]
```css
.grid {
    display: grid;
    grid-template-columns: repeat(12, calc(100% / numberOfColumns));
    grid-template-rows: repeat(12, calc(100% / numberOfRows));
    width: 100%;
    height: 100%;
}

.gridItem {
    grid-column-start: x;
    grid-column-end: x + width;
    grid-row-start: y;
    grid-row-end: y + height;
}
```
This is a simple example of a grid using CSS grid, I tried using this before I moved to your JS solution. But I am having issues with Gridstack, like not being able to make the whole grid be 100vh height and setting the cellHeight to 'auto'. I also tried setting the cellHeight to `${100 / 12}vh` but that still does not work as supposed.

**Comment by sebastianwebb** [comment]
> @sebastianwebb could you give a concrete example and what the benefit would be ?
> 
> right now the output CSS from sass looks like this for 12 column default
> 
> ```css
> .grid-stack > .grid-stack-item {
>   min-width: 8.3333333333%;
>   position: absolute;
>   padding: 0;
> }
> 
> .grid-stack>.grid-stack-item[data-gs-width='1'] {
>   width: 8.3333333333%;
> }
> .grid-stack>.grid-stack-item[data-gs-x='1'] {
>   left: 8.3333333333%;
> }
> .grid-stack>.grid-stack-item[data-gs-min-width='1'] {
>   min-width: 8.3333333333%;
> }
> .grid-stack>.grid-stack-item[data-gs-max-width='1'] {
>   max-width: 8.3333333333%;
> }
> .grid-stack>.grid-stack-item[data-gs-width='2'] {
>   width: 16.6666666667%;
> }
> .grid-stack>.grid-stack-item[data-gs-x='2'] {
>   left: 16.6666666667%;
> }
> .grid-stack>.grid-stack-item[data-gs-min-width='2'] {
>   min-width: 16.6666666667%;
> }
> .grid-stack>.grid-stack-item[data-gs-max-width='2'] {
>   max-width: 16.6666666667%;
> }
> etc...
> ```

Thanks for getting back to me. It's been a while since I posted so unfortunately I've forgotten my use case. But on further experimentation with the tool and I think absolute position might be better anyway. Grid column positions do not animate, unlike 'left', 'top', 'width', and 'height', which could be a bit limiting.

**Comment by adumesny** [comment]
@sebastianwebb thanks, and good to know. Will keep this open for info and feedback...

**Comment by RadoiAndrei** [comment]
The concept is simple, the `grid-stack` element will have the following properties:
```css
.grid-stack {
  display: grid /* Or inline-grid, if inline-grid it will also have a width */;
  grid-auto-columns: 1fr;
  grid-auto-rows: 20px;
}
```
then we can have each grid-stack-item have it's position set from js using style:
```js
item.style.gridColumnStart = x;
item.style.gridColumnEnd = x + width;
item.style.gridRowStart = y;
item.style.gridRowEnd = y + height;
```
The harder part, that I kind of have an idea already on how would work is the drag'n'drop which could be done something like:
```
// Pseudocode
dropCellX = Math.round(drop.x / cellWidth)
dropCellY = Math.round(drop.y / cellHeight)
```

It would need major rewritting of the engine I guess, but it will make everyone's life wayyy easier in the end imo.
