### ISSUE TITLE
[Proposal] - Using fractional units like TailwindCSS instead use 12 Column

### ISSUE THREAD

**Issue by lamualfa** [gridstack/gridstack.js#1448]
### Description

Using fractional units like TailwindCSS is easier to read and understand than using 12 Column units like the Bootstrap.

### Example with Fractional Unit

```css
.grid-stack-item[data-gs-width="full"]  { width: 100% }
.grid-stack-item[data-gs-width="1/2"]  { width: 50% }
.grid-stack-item[data-gs-width="1/4"]  { width: 25% }

.grid-stack-item[data-gs-width="1/12"]  { width: 8.333% }
.grid-stack-item[data-gs-width="2/12"]  { width: 1.666% }
```

#### Details

- `full` symbol used for **100%**.
- `1/2` used for **50%** because `1` divided by `2` is **0.5**. **0.5** is **50%** of `1`.
- `1/4` used for **25%** because `1` divided by `4` is **0.25**. **0.25** is **25%** of `1`.
- Etc.
