### ISSUE TITLE
The column parameter leads to incorrect column placement & detection

### ISSUE THREAD

**Issue by ghusse** [gridstack/gridstack.js#1749]
## Subject of the issue
When specifying a different value for the parameter `column`, gridstack does not correctly compute the location of widgets, and does not detect correctly widget's position on drag & drop.

## Your environment
- gridstack 4.2.0 with HTML5 version and jquery (the same bug is present) 
- Chromium 92.0.4476.0 and Firefox 88.0

## Steps to reproduce

Here are codepens that reproduce this issue: 
- HTML5: https://codepen.io/ghusse/pen/PoWLgaG
- jQuery: https://codepen.io/ghusse/pen/qBRvGjb

```js
var items = [
  { content: "my first widget" },
  { w: 2, content: "another longer widget!" }
];
var grid = GridStack.init({
  column: 5
});
grid.load(items);

```

![gridstack-column](https://user-images.githubusercontent.com/527245/116215576-18c54f00-a748-11eb-84e1-145e345ae3f5.gif)

## Expected behavior
The grid must be separated into 5 larger columns (each one having a width of 1/5 of the total available width, minus the margins).

## Actual behavior
The columns seem to keep the same width, but drop detection seem to detect drop position approximatively correctly

**Comment by ghusse** [comment]
It seems to be fixed by this code:

```scss
$gridstack-columns: 12 !default;

.grid-stack {
  @for $total-columns from 2 through $gridstack-columns{
    &.grid-stack-#{$total-columns} {
      @for $i from 0 through $gridstack-columns {
        [gs-w='#{$i}'] { width: (100% / $total-columns) * $i; }
        [gs-x='#{$i}'] { left: (100% / $total-columns) * $i; }
        [gs-min-w='#{$i}'] { min-width: (100% / $total-columns) * $i; }
        [gs-max-w='#{$i}'] { max-width: (100% / $total-columns) * $i; }
      }
    }
  }
}
```

This will generate correct css rules for all numbers of columns between 2 and 12
