### ISSUE TITLE
Feat Request: Know when a grid is moved from a nested grid to a parent grid from added event

### ISSUE THREAD

**Issue by fredericrous** [gridstack/gridstack.js#2220]
## Subject of the issue

Every time I move a widget from a nested grid to it's parent or vis versa, it triggers a "added" event.
I configured my app to rerender a widget on every added event because I use an external rendering lib.

I receive an event that looks like

```yaml
isTrusted: false
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: div.grid-stack.grid-stack-r1.grid-stack-instance-1.grid-stack-animate.ui-droppable.ui-droppable-over
defaultPrevented: false
detail: [{
  el: div.grid-stack-item
  grid: GridStack {_gsEventHandler: {…}, _extraDragRow: 0, el: div.grid-stack.grid-stack-r1.grid-stack-instance-1.grid-stack-animate.ui-droppable.ui-droppable-over, opts: {…}, _isAutoCellHeight: true, …}
  h: 8
  id: 1677136040731
  w: 8
  x: 4
  y: 3
  _id: 5
}]
eventPhase: 2
path: (7) [div.grid-stack.grid-stack-r1.grid-stack-instance-1.grid-stack-animate.ui-droppable.ui-droppable-over, div.App, div#root, body, html, document, Window]
returnValue: true
srcElement: div.grid-stack.grid-stack-r1.grid-stack-instance-1.grid-stack-animate.ui-droppable.ui-droppable-over
target: div.grid-stack.grid-stack-r1.grid-stack-instance-1.grid-stack-animate.ui-droppable.ui-droppable-over
timeStamp: 226682.2000002861
type: "added"
```

## Your environment
* version of gridstack.js: v7.2.3
* which browser/OS: all

## Expected behavior

I whish I could differentiate easily from within the added event between the event "added new widget on the grid" and "moved a widget from a grid to another"

I would receive an additional property:

```yaml
detail: [{
  ... ,
  originGridId: grid-stack-r3
}]
```

with this information I could compare with target(?)'s class names and know from there that it is the same grid or not and decide from there if I want to rerender the widget I control or not.
