### ISSUE TITLE
remove min-max CSS

### ISSUE THREAD

**Issue by adumesny** [gridstack/gridstack.js#2243]
## Subject of the issue

today we use CSS for min/max but I really don't see why since the interaction is in code and not using CSS to contrain - might as well only set it during resizing on the clone if at all...

```scss
@use "sass:math";
.grid-stack > .grid-stack-item {

  $gridstack-columns: 12;

  min-width: 100%/$gridstack-columns;

  @for $i from 0 through $gridstack-columns {
    &[gs-w='#{$i}'] { width: (100% / $gridstack-columns) * $i; }
    &[gs-x='#{$i}'] { left: (100% / $gridstack-columns) * $i; }
    &[gs-min-w='#{$i}'] { min-width: (100% / $gridstack-columns) * $i; }
    &[gs-max-w='#{$i}'] { max-width: (100% / $gridstack-columns) * $i; }
  }
} 
```
