### ISSUE TITLE
Fixed grid widths - drag offset

### ISSUE THREAD

**Issue by RodTGG** [gridstack/gridstack.js#2875]
## Widget offset doesnt align
Sorry if im in the wrong place

Im attempting to make a fixed width grid so ive done some custom scss nothing too fancy.

Just setting width and left so that i can a fixed number of columns that can be overflowed horizontally

``` scss

$nColumns: 15;

$colWidth: 17rem;

.gridstack-fixed
{
    overflow-x: auto;
    overflow-y: hidden;

    > .grid-stack-item-fixed {

        width: $colWidth;
      
        @for $i from 1 through $nColumns - 1 {
          &[gs-x='#{$i}'] { left: $i * $colWidth; }
          &[gs-w='#{$i}'] { width: $colWidth * $i; }
        }
    }
}

```

However, when i try and drag the widgets the x offset seems to grow exponentially and not align with cursor properly. e.g. if i grab a widget at x=3 and hold it over x=6 the placeholder is all the way at x=8 or so. Then when dropped it drops at x=8.

## Your environment
gridstack: 11.1.0
chrome: 131.0.6778.69
windows 10: 19045.5131

## Steps to reproduce
set a fixed width and left based on example on readme
https://jsfiddle.net/simpledev/38tLswkr/

## Expected behavior
Placeholder and mouse tracking to follow mouse
