### ISSUE TITLE
Grids not get smaller on mobile for cards

### ISSUE THREAD

**Issue by mralperem** [gridstack/gridstack.js#2883]
Hi, I tried to implement grid stack with card collapse uncollapse feature but in mobile the widgets are not respetcing the min width thus make it look too much gap between widgets

![desktop](https://github.com/user-attachments/assets/d6fa7af1-fc07-4f46-ac52-3e570a434d52)
![Untitled](https://github.com/user-attachments/assets/3ff78aa5-b984-4e87-ac70-bbcc088b9aef)

But on dekstop it works perfect why this is happening is this a bug?

My code as follows 

```ts
$(document).ready(function() {

    $(".circular-menu-toggle").click(() => {
        $(".circular-menu-toggle, .circular-menu, .vertical-menu-group").toggleClass("open");
    });

    const grid = GridStack.init({
        float: false,
        column: 12, 
        cellHeight: 'auto',
        animate: false,
        oneColumnSize: 767.98 
    });

    grid.on('resizestop', function(event, el) {
        const newHeight = el.getAttribute('gs-h');
        el.setAttribute('data-original-height', newHeight);
    });

    $(".grid-stack").on("click", ".toggle-collapse", toggleCardCollapse);
    $(".grid-stack").on("click", ".close-card", closeCard);
    $(".grid-stack").on("click", ".toggle-expand", toggleCardExpand);

    $("#add-user-task-card").click(() => {
        const userTaskContent = `
            <tr><td>Create Task</td><td class="text-center">📋</td><td>Details about creating tasks</td></tr>
        `;
        createCard("user-task", userTaskContent, { width: 4, height: 4, minWidth: 2, minHeight: 1 }, "User Task");
    });

    $("#add-jobs-card").click(() => {
        const jobContent = `
            <tr><td>Create Job</td><td class="text-center">💼</td><td>Details about creating jobs</td></tr>
        `;
        createCard("jobs", jobContent, { width: 4, height: 2, minWidth: 2, minHeight: 1 }, "Jobs");
    });

    $("#add-company-card").click(() => {
        const companyContent = `
            <tr><td>Create Company</td><td class="text-center">🏢</td><td>Details about creating companies</td></tr>
        `;
        createCard("company", companyContent, { width: 4, height: 2, minWidth: 2, minHeight: 1 }, "Company");
    });

    $("#add-customer-card").click(() => {
        const customerContent = `
            <tr><td>Create Customer</td><td class="text-center">🤝</td><td>Details about creating customers</td></tr>
        `;
        createCard("customer", customerContent, { width: 4, height: 2, minWidth: 2, minHeight: 1 }, "Customer");
    });

    function createCard(cardType, cardContent, { width, height, minWidth, minHeight }, title) {
        const cardHtml = `
            <div class="card card-action h-100">
                <div class="card-header">
                    <h5 class="card-action-title mb-0">${title}</h5>
                    <div class="card-action-element">
                        <button class="btn btn-sm btn-icon toggle-collapse">
                            <svg class="icon icon-sm">
                                <use href="../assets/images/icons/sprite.svg#chevron-down"></use>
                            </svg>
                        </button>
                        <button class="btn btn-sm btn-icon toggle-expand">
                            <svg class="icon icon-sm">
                                <use href="../assets/images/icons/sprite.svg#arrows-maximize"></use>
                            </svg>
                        </button>
                        <button class="btn btn-sm btn-icon close-card">
                            <svg class="icon icon-sm">
                                <use href="../assets/images/icons/sprite.svg#x"></use>
                            </svg>
                        </button>
                    </div>
                </div>
                <div class="collapse show">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Action</th>
                                <th class="text-center">Icon</th>
                                <th>Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${cardContent}
                        </tbody>
                    </table>
                </div>
            </div>`;

        const newItem = grid.addWidget({
            x: 0,
            y: 0,
            w: width,
            h: height,
            minW: minWidth,
            minH: minHeight,
            autoPosition: true
        });
        newItem.setAttribute("data-original-height", height);
        newItem.querySelector('.grid-stack-item-content').innerHTML = cardHtml;
    }

    function closeCard(e) {
        e.preventDefault();
        const gridItem = $(e.target).closest(".grid-stack-item");
        grid.removeWidget(gridItem[0]);
    }

    function toggleCardCollapse(e) {
        e.preventDefault();
        const gridItem = $(e.target).closest(".grid-stack-item");
        const card = gridItem.find(".card");
        const collapseElement = card.find(".collapse");
        const isExpanded = collapseElement.hasClass("show");

        if (isExpanded) {
            if (!gridItem.attr("data-original-height")) {
                const currentHeight = gridItem.data("gs-height");
                gridItem.attr("data-original-height", currentHeight);
            }
            grid.update(gridItem[0], { h: 1 });
        } else {
            const originalHeight = gridItem.attr("data-original-height");
            if (originalHeight) {
                grid.update(gridItem[0], { h: parseInt(originalHeight, 10) });
            }
        }

        collapseElement.toggleClass("show");
        toggleIcon(e.target, isExpanded ? "chevron-right" : "chevron-down");
    }

    function toggleCardExpand(e) {
        e.preventDefault();
        const card = $(e.target).closest(".card");
        const isFullscreen = card.hasClass("card-fullscreen");

        card.toggleClass("card-fullscreen");
        toggleIcon(e.target, isFullscreen ? "arrows-maximize" : "arrows-minimize");
    }

    function toggleIcon(target, iconId) {
        const icon = $(target).find("use");
        icon.attr("href", `../assets/images/icons/sprite.svg#${iconId}`);
    }

    const options = {
        columns: [
            { label: 'Name', type: 'text', width: '250px', minwidth: '250px' },
            { label: 'Date', type: 'date', width: '150px', minwidth: '150px' },
            { label: 'Status', type: 'status', width: '150px', minwidth: '150px' },
            { label: 'Type', type: 'text', width: '150px', minwidth: '150px' },
            { label: 'Due Date', type: 'date', width: '150px', minwidth: '150px' }
        ],
        data: [
            { '0': 'Task 1', '1': '08/04/2024', '2': 'completed', '3': 'email1', '4': '08/05/2024' },
            { '0': 'Task 2', '1': '08/04/2024', '2': 'done', '3': 'email2', '4': '08/05/2024' },
            { '0': 'Task 3', '1': '08/04/2024', '2': 'done', '3': 'email3', '4': '08/05/2024' }
        ],
        enableComment: true,
        enableRowAdd: true,
        enableRowEdit: true,
        enableColumnEdit: true,
        enableColumnResize: true,
        enableRowSwap: true,
        enableColumnSwap: true,
        enableColumnAdd: true
    };
    new InteractiveTable('.add-task-table', options);
});
```

```css
.grid-stack-item-content {
    border-radius: 0.375rem;
    overflow: hidden !important;
}

.gs-id-0>.grid-stack-item:has(.collapsed-grid-item) {
    height: 80px !important;
}

.grid-stack-item-content .card-body {
    padding: 1.5rem 1.5rem 1rem 1.5rem;
    overflow-x: hidden;
    overflow-y: auto;
    transition: padding 0.3s ease-in-out;
}

.grid-stack-item-content .card-header {
    padding: 1.2rem 1.5rem 0 1.5rem;
}

.circular-menu-toggle {
    display: flex;
    position: fixed;
    align-items: center;
    justify-content: center;
    bottom: 2rem;
    right: 1rem;
    background-color: var(--primary-color);
    color: #fff;
    width: 45px;
    height: 45px;
    border-radius: 50%;
    box-shadow: var(--box-shadow-sm);
    z-index: 5;
    cursor: pointer;
}

.circular-menu-toggle-icon svg {
    transition: transform 0.3s;
}

.circular-menu-toggle.open .circular-menu-toggle-icon svg {
    transform: rotate(135deg);
}

.vertical-menu-group {
    position: fixed;
    bottom: 2rem;
    right: 1rem;
    z-index: 2;
}

.circular-menu a:hover,
.vertical-menu-group a:hover {
    color: #fff;
}

.circular-menu {
    position: fixed;
    bottom: 2rem;
    right: 1rem;
    z-index: 3;
}

.circular-menu-button {
    display: flex;
    position: fixed;
    bottom: 2rem;
    right: 1rem;
    align-items: center;
    justify-content: center;
    width: 2.5rem;
    height: 2.5rem;
    background-color: var(--primary-color);
    color: #fff;
    border-radius: 50%;
    transition: all 0.3s ease-in-out;
    transition-delay: 0s;
    cursor: pointer;
}

.vertical-menu-group .circular-menu-button {
    transition: all 0.3s ease-in-out;
    transition-delay: 0.3s;
}

.circular-menu.open .circular-menu-button:nth-of-type(1) {
    right: 1rem;
    bottom: 5.75rem;
    transition-delay: 0.1s;
}

.circular-menu.open .circular-menu-button:nth-of-type(2) {
    right: 4rem;
    bottom: 4.25rem;
    transition-delay: 0.2s;
}

.circular-menu.open .circular-menu-button:nth-of-type(3) {
    right: 4.75rem;
    bottom: 1rem;
    transition-delay: 0.3s;
}

.vertical-menu-group .circular-menu-button {
    bottom: 2.25rem;
    transition-delay: 0s;
}

.vertical-menu-group.open .circular-menu-button:nth-of-type(1) {
    bottom: 8.75rem;
    transition-delay: 0.2s;
}

.vertical-menu-group.open .circular-menu-button:nth-of-type(2) {
    bottom: 11.75rem;
    transition-delay: 0.3s;
}

.vertical-menu-group.open .circular-menu-button:nth-of-type(3) {
    bottom: 14.75rem;
    transition-delay: 0.4s;
}
/* END: Dashboard Styles */

```
