### ISSUE TITLE
Question: Missing margin between items and drag not taking size into consideration at all

### ISSUE THREAD

**Issue by realhydroper** [gridstack/gridstack.js#3004]
This time I'm posting an example without React. I have two following issues as demonstrated by the GIF:

![Image](https://github.com/user-attachments/assets/c752a548-3ebc-493c-915e-28e03e38952c)

As you can see, 1) drag-n-drop is both not showing the correct drop area and not snapping correctly, and 2) margin between items just does not exist.

Note that dragging-and-dropping far away works as expected (indeed seems like GridStack.js is not taking into consideration the actual "tile" or cell width).

I expected the `margin` option to be "margin between items", but it doesn't seem to effect. And I also expected my style's width to be fully taken into consideration while dragging grid items.

```ts
// Initialize GridStack
this._gridstack = GridStack.init(
  {
    draggable: {
      handle: "." + this._tile_class_name,
    },
    handleClass: this._tile_class_name,
    itemClass: this._tile_class_name,
    rtl: options.rtl,
    margin: "0.6rem",
    cellHeight: "3.625rem",
    maxRow: options.maxRow,
    float: true,
    alwaysShowResizeHandle: false,
    disableResize: true,
  },
  this._container
);
```

Style:

```css
.gs-12 {
    --gs-cell-width: 3.625rem;
    --gs-gap: 0.6rem;
}

.gs-12 > .grid-stack-item { width: var(--gs-cell-width) !important }
.gs-12 > .grid-stack-item[gs-w="2"]  { width: calc(calc(var(--gs-cell-width) * 2) + var(--gs-gap)) !important }
.gs-12 > .grid-stack-item[gs-w="4"]  { width: calc(calc(var(--gs-cell-width) * 4) + calc(var(--gs-gap) * 2)) !important }
```

Note, here `--gs-gap` should be the equivalent of the above `margin` option given to `GridStack.init({ ... }, el)`.

[Playground](https://codesandbox.io/p/github/realhydroper/tilelayoutgs/master?import=true) (note the `demo` directory contains the actual usage of the library around GridStack.js).

I also have forked this repository because the library was ignoring dragging on `button` elements (my grid items are buttons, so had to change the code part doing that restriction).
