### ISSUE TITLE
TwoColumnMode

### ISSUE THREAD

**Issue by LiamEngland** [gridstack/gridstack.js#979]
OneColumnMode is good however when using it at a wide viewport it doesn't look too good, as I've tried setGridWidth but on resize it's not functioning well at all, so was wondering if there'd be a possibility to add a twoColumnMode so it'd be able to be manipulated at certain viewports to add more responsiveness.

I'm using gridstack via NPM v 0.4.0
Browser being used is Opera 58.0.3135.79

**Comment by gooeyideas** [comment]
You can easily achieve this yourself with css:
```css
.grid-stack.grid-stack-responsive-column-mode {
  height: auto !important;
  display: flex;
  flex-wrap: wrap;
}
.grid-stack.grid-stack-responsive-column-mode > .grid-stack-item {
  position: relative !important;
  left: 0 !important;
  top: auto !important;
  margin-bottom: 20px;
  max-width: none !important;
  width: 50% !important;
  flex: 1 1 50%;
}
@media (max-width: 568px) {
  .grid-stack.grid-stack-responsive-column-mode > .grid-stack-item {
    width: 100% !important;
    flex: 1 1 100%;
  }
}
.grid-stack.grid-stack-responsive-column-mode > .grid-stack-item > .ui-resizable-handle {
  display: none;
}
``` 
```js
    $(gridstackEl).gridstack({
      cellHeight: 80,
      verticalMargin: 20,
      horizontalMargin: 10,
      oneColumnModeClass: "grid-stack-responsive-column-mode"
    });
```

Here is a codepen demo: https://codepen.io/GooeyIdeas/pen/ywPNQG?editors=0110
